# Generated by Django 5.2.4 on 2025-12-01 10:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import menu.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title_en', models.CharField(max_length=120, verbose_name='title (EN)')),
                ('title_fa', models.CharField(max_length=120, verbose_name='title (FA)')),
                ('description_en', models.TextField(blank=True, verbose_name='description (EN)')),
                ('description_fa', models.TextField(blank=True, verbose_name='description (FA)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('display_order',),
                'abstract': False,
            },
            bases=(models.Model, menu.models.TranslatableFieldsMixin),
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=120, verbose_name='site name')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='logo')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='favicon')),
                ('hero_headline_en', models.CharField(blank=True, max_length=180, verbose_name='hero headline (EN)')),
                ('hero_headline_fa', models.CharField(blank=True, max_length=180, verbose_name='hero headline (FA)')),
                ('hero_subtitle_en', models.CharField(blank=True, max_length=220, verbose_name='hero subtitle (EN)')),
                ('hero_subtitle_fa', models.CharField(blank=True, max_length=220, verbose_name='hero subtitle (FA)')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=40, verbose_name='contact phone')),
                ('contact_whatsapp', models.CharField(blank=True, max_length=80, verbose_name='whatsapp')),
                ('address_en', models.CharField(blank=True, max_length=220, verbose_name='address (EN)')),
                ('address_fa', models.CharField(blank=True, max_length=220, verbose_name='address (FA)')),
                ('opening_hours', models.CharField(default='08:00 - 23:00', max_length=180, verbose_name='opening hours')),
                ('footer_text_en', models.CharField(blank=True, max_length=200, verbose_name='footer text (EN)')),
                ('footer_text_fa', models.CharField(blank=True, max_length=200, verbose_name='footer text (FA)')),
                ('footer_links', models.JSONField(blank=True, default=list, verbose_name='footer links')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='social links')),
                ('seo_description_en', models.TextField(blank=True, verbose_name='SEO description (EN)')),
                ('seo_description_fa', models.TextField(blank=True, verbose_name='SEO description (FA)')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name_en', models.CharField(max_length=140, verbose_name='name (EN)')),
                ('name_fa', models.CharField(max_length=140, verbose_name='name (FA)')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('description_en', models.TextField(blank=True, verbose_name='description (EN)')),
                ('description_fa', models.TextField(blank=True, verbose_name='description (FA)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price')),
                ('currency', models.CharField(choices=[('IRR', 'Iranian Rial'), ('USD', 'US Dollar')], default='IRR', max_length=3, verbose_name='currency')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/items/', verbose_name='image')),
                ('is_signature', models.BooleanField(default=False, verbose_name='signature item')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='calories')),
                ('preparation_time', models.CharField(blank=True, max_length=40, verbose_name='prep time')),
                ('highlight_badge_en', models.CharField(blank=True, max_length=60, verbose_name='badge (EN)')),
                ('highlight_badge_fa', models.CharField(blank=True, max_length=60, verbose_name='badge (FA)')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Optional public rating displayed on the card', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='rating')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menucategory')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
                'ordering': ('category', 'name_en'),
                'abstract': False,
            },
            bases=(models.Model, menu.models.TranslatableFieldsMixin),
        ),
    ]
