# Generated by Django 5.2.8 on 2025-12-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='site_name',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/categories/', verbose_name='cover image'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_en',
            field=models.CharField(default=1, max_length=120, verbose_name='site name (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_fa',
            field=models.CharField(blank=True, max_length=120, verbose_name='site name (FA)'),
        ),
    ]
